### ISSUE TITLE
import components fails

### ISSUE THREAD

**Issue by ggbhat** [jagreehal/typescript-jest-boilerplate#3]
when I tried to import components like import '@ui5/webcomponents/dist/Button'; in index.ts
below error shown:
 _```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import UI5Element from "@ui5/webcomponents-base/src/UI5Element.js";
                                                                                                    ^^^^^^^^^^

    SyntaxError: Unexpected identifier

      1 |
      2 | require('source-map-support').install();
    > 3 | import '@ui5/webcomponents/dist/Button';
        | ^
      4 | import '@ui5/webcomponents/dist/Input';
      5 | import '@ui5/webcomponents/dist/Label';
      6 | import '@ui5/webcomponents/dist/Dialog';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at Object.<anonymous> (src/index.ts:3:1)
```_

**Comment by jagreehal** [comment]
this should be fixed by https://github.com/jagreehal/typescript-jest-boilerplate/pull/4
